---
- name: LAMP Stack Setup
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache, PHP, and required modules
      apt:
        name:
          - apache2
          - php
          - libapache2-mod-php
        state: present

    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present

    - name: Start and enable Apache
      systemd:
        name: apache2
        state: started
        enabled: yes

    - name: Start and enable MySQL
      systemd:
        name: mysql
        state: started
        enabled: yes
