- name: Deploy LAMP with MySQL using Docker
  hosts: all
  become: yes

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Copy project files
      copy:
        src: /home/vboxuser/Desktop/lamp-devops-ci-cd/
        dest: /home/vboxuser/app/
        remote_src: no

    - name: Run Docker Compose
      command: docker-compose up -d --build
      args:
        chdir: /home/vboxuser/app/
