name: CI/CD for LAMP App

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t my-lamp-app -f docker/Dockerfile .
          
      - name: Run Docker container
        run: |
          docker run -d -p 8080:80 my-lamp-app

